name: Artifact workflow

on:
  push:
    paths:
      -  ".github/workflows/artifact.yml"

jobs:
  build_artifact:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir output
      - run: echo "Hello from artifact" > output/hello.txt
      - uses: actions/upload-artifact@v4
        with:
          name: uploading
          path: output/

  test_artifact:
    needs: build_artifact
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing artifact"
      - uses: actions/download-artifact@v4
        with:
          name: uploading
      - run: ls -R
      - run: cat uploading/hello.txt
