name: second file for github actions

on: push

jobs:
  secondpush:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "first step running"

      - name: second step
        run: echo "second step running"

      - name: third step
        run: echo "third step running"
